# Generated by Django 2.2.8 on 2019-12-15 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название дистрибьютора')),
                ('recipient_first_name', models.CharField(max_length=30, verbose_name='Имя получателя')),
                ('recipient_last_name', models.CharField(max_length=30, verbose_name='Фамилия получателя')),
                ('recipient_patronymic', models.CharField(blank=True, max_length=30, verbose_name='Отчество получателя')),
                ('shipping_address', models.CharField(max_length=150, verbose_name='Адрес отправки карты')),
                ('telephone_number', models.CharField(max_length=25, verbose_name='Телефонный номер')),
                ('external_id', models.CharField(max_length=25, unique=True, verbose_name='Внешний ID из 1С')),
                ('region', models.CharField(max_length=25, verbose_name='Аббревиатура регионов')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время добавления')),
                ('active', models.BooleanField(default=True, verbose_name='Статус удален/активен')),
            ],
        ),
    ]
